name: CI Kubernetes

on: [push]

jobs:
  k8s-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create Kind Cluster
        uses: helm/kind-action@v1.8.0

      - name: Build Image
        run: docker build -t meu-app-local:v1 .

      - name: Load Image into Kind
        run: |
          # Esse comando pega o nome do cluster que acabou de ser criado
          CLUSTER_NAME=$(kind get clusters)
          kind load docker-image meu-app-local:v1 --name $CLUSTER_NAME

      - name: Deploy to K8s
        run: |
          kubectl apply -f k8s-deployment.yaml
          kubectl wait --for=condition=ready pod -l app=meu-app --timeout=90s
          kubectl logs -l app=meu-app