name: Cluster Public IP
on: [push]

jobs:
  run-cluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar Dependências
        run: |
          npm install -g tsx localtunnel

      - name: Rodar Cluster e Abrir IP
        run: |
          tsx app.ts &
          sleep 5
          lt --port 8000