name: Cluster Public IP
on: [push]

jobs:
  run-cluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar Ferramentas
        run: npm install -g tsx localtunnel

      - name: Obter IP e Rodar Cluster
        run: |
          tsx app.ts &
        
          sleep 5
          
          echo "------------------------------------------"
          echo "A TUA TUNNEL PASSWORD É:"
          curl https://loca.lt/mytunnelpassword
          echo "------------------------------------------"
          
         
          lt --port 8000