name: Testar Cluster Learning
on: [push]

jobs:
  execucao-cluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Rodar Código
        run: npx ts-node app.ts